import { Permission } from '../../../auth/model/permissions.model';

export interface IUser {
  id: number;
  provider: string;
  uid: string;
  allow_password_change: boolean;
  name: string;
  nickname: string;
  zzz_image?: null | string;
  email: string;
  created_at: string;
  updated_at: string;
  admin?: null | boolean;
  referral_token?: null | string;
  referred_by?: null | string;
  website?: null | string;
  city?: null | string;
  showimage: boolean;
  showcity: boolean;
  showname: boolean;
  showwebsite: boolean;
  gender: 0 | 1;
  signup_form_shown: boolean;
  stripe_user_id?: null | number;
  advisorrate: number;
  lang: null | string;
  stripe_customer_id: null | number;
  showtutorials: boolean;
  sharetoken: null | string;
  zzz_profileimage: null | string;
  isteam: boolean;
  time_zone: string;
  online: boolean;
  websocket_connect: boolean;
  allow_contact_without_stripe: boolean;
  video_chat_allowed: boolean;
  live_chat_allowed: boolean;
  appointments_auto_confirmation: boolean;
  image: null | string;
  profileimage: null | string;
  pinned_advisors: [];
  select_comments_by_default: boolean;
  username: string;
  about?: object | null;
  conversation_id: null | number;
  permissions: Permission[];
  display_name?: string;
  conversations_muted: boolean;
}
